image: eclipse-temurin:21-jdk

stages:
  - build

before_script:
  - chmod 777 gradlew

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  script:
    ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar